export enum Stage {
  QUALIFICATION = 'QUALIFICATION',

  NEEDS_ANALYSIS = 'NEEDS_ANALYSIS',

  VALUE_PROPOSITION = 'VALUE_PROPOSITION',

  IDENTIFY_DECISION_MAKERS = 'IDENTIFY_DECISION_MAKERS',

  PROPOSAL = 'PROPOSAL',

  PRICE_QUOTE = 'PRICE_QUOTE',

  NEGOTIATION = 'NEGOTIATION',

  REVIEW = 'REVIEW',

  CLOSED_WON = 'CLOSED_WON',

  CLOSED_LOST = 'CLOSED_LOST',

  CLOSED_LOST_TO_COMPETITION = 'CLOSED_LOST_TO_COMPETITION',
}
